application: yugdom-gae
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: app.application

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest